version: "3"

services:
  influxdb:
    image: influxdb:2.4
    container_name: influxdb
    volumes:
      - ${PATH}/influxdb:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: unless-stopped
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      - localnet

  telegraf:
    image: telegraf:1.24
    container_name: telegraf
    volumes:
      - ${PATH}/telegraf:/etc/telegraf:rw
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - influxdb
    networks:
      - localnet

  grafana:
    image: grafana/grafana-oss:9.1.5
    container_name: grafana
    volumes:
      - ${PATH}/grafana:/var/lib/grafana:rw
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - localnet
        
networks:
  localnet:
    external:
      name: localnet
